### ISSUE TITLE
HW1 Feedback

### ISSUE THREAD

**Issue by jvictorchen** [Suri-Sun/baruch-mfe-python-summer#1]
* countwords has a bug. In the following example, it will return 4. Can you see why?
```
%%countwords this
is a cell magic
```
* List comprehension: use `timeit` would give you more stable result.
* Prime numbers: you're implementing odd numbers, not prime numbers?
* Vector
  * `self.ls = [_ for _ in elements]` -> `self.data = list(elements)`. Actually storing the tuple would be better.
  * `__add__/__mul__/__pow__` are not correct. Check your last example of using `__pow__` more carefully?
* Case insensitive dictionary: 
  * `proxy = {}`. This is a class attribute and will be shared by all instances of `CaseInsensitiveDict`. That's probably not what we want. 
  * `__repr__` should return a more unique representation of the object. 
 
Score: B

**Comment by Suri-Sun** [comment]
Hi Victor,

Thanks for your thorough comments. I just got a few more questions:

1. In the cell magic, I redid it as
`return len(line.split()+cell.split())` and it returns the expected answer. But I'm not sure why. Do you mind explaining a bit?

2. For dunder operations, I return `Vector(*data)`. Is it what you meant for?

3. For CaseInsensitiveDict, I tried to hash case-insensitively equal keys to the same position, then both getter and setter would be case-insensitive. Is it what we want?

btw, I uploaded the revised work, and I really appreicate if you can take a look.

Lots of thanks
Suri

**Comment by jvictorchen** [comment]
1. because `line` does not have '\n' in the end but `cell` does have it. If you join the two with `line + cell` then the last word will be concatenated with the first word of `cell`. 
2. Correct
3. That would work. Your `__init__` method is still not correct. Take a look at `UserDict` to see the signature of `__init__`? Also a few other dunder methods need to be implemented to make `UserDict` feature complete, such as `__contains__` and `__delitem__`, `__iter__`, etc.
